### ISSUE TITLE
Refresh interval

### ISSUE THREAD

**Issue by AjaxSolutions** [mauricedb/use-abortable-fetch#223]
What would be the easiest way to call this hook in an abortable and restartable loop every refreshInterval milliseconds?

Could this config option be added to the hook?

**Comment by mauricedb** [comment]
Interesting question. My first impression is that you would want to use something like RxJS with an interval based observable instead of `use-abortable-fetch`.

With `use-abortable-fetch` I have not done it but the normal flow is a component (re)renders and requests data. So I would have the component rerender based on a state changee from a `setInterval()`. And the you would have to update either the URL or the optional `RequestInit` parameter because no fetch occurs if they are the same. Often I would add some timestamp to the URL with a value of `Date.now()` to prevent browser caching etc.
