### ISSUE TITLE
Why there is a check if the component is mounted?

### ISSUE THREAD

**Issue by AjaxSolutions** [mauricedb/use-abortable-fetch#224]
I'm just trying to understand the codebase better.

I'm curious why the hook is checking if the component is mounted before setting state data, see [line 17](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/index.ts#L17)

I'm asking because the fetch is aborted when the component is unmounted.

**Comment by mauricedb** [comment]
@AjaxSolutions 

Basicaly there are two reasons.

1. Functionally there is no point in requesting data if the component that requested it is unmounted and no longer interested in it. Most API's are going ignore the abort but some will even stop processing on the server if this happens.
2. If you set state on an unmounted component you will get a nasty and scary error message in the browsers console. In this case it probably isn't much of an issue but the message is there because it can be a memory/resource leak like forgetting to stop a `setInterval()`.

HTH

**Comment by dmargolies** [comment]
The `fetch` is aborted on line 42, which should occur when the component is unmounted. I don't follow why we'd also need to check if the component has been unmounted. Is there a race condition here?

**Comment by mauricedb** [comment]
Yes there is. The call to get the [JSON](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/fetchData.ts#L32) is also async so the AJAX call can be complete before the components unmounts while the state update occurs after the component unmounts.
